skywind_url: 'https://api.github.com/gists/5338904'
skyblivion_url: 'https://api.github.com/gists/5338932'
installer_thread: 'http://morroblivion.com/forums/skyrim/skywind-development/4098'
debug: True