debug: false
first_run: true
installer_thread: http://morroblivion.com/forums/skyrim/skywind-development/4098
skyblivion_url: https://api.github.com/gists/5338932
skywind_url: https://api.github.com/gists/5338904
