readme: !mapping
    style: !!python/unicode 'dark'
    url: !!python/unicode 'http://morroblivion.com/forums/skyrim/skyblivion-mod-releases/4122'
    xpath: !!python/unicode '//*[@id="node-4122"]/div[2]/div[2]/div'
versions: !mapping
    0.6.0: !mapping
        components: !mapping
            test.7z: !mapping
                dest: !!python/unicode 'Data'
                hash: false
                optional: true
                type: !!python/unicode 'archive'
    0.6.1: !mapping
        components: !mapping
            test.7z: !mapping
                dest: !!python/unicode 'Data'
                hash: false
                optional: true
                type: !!python/unicode 'archive'
