readme:
    url: http://morroblivion.com/forums/skyrim/archived-topics/4195
    xpath: '//*[@id="node-4195"]/div[2]/div[2]/div'
    style: 'dark'
versions:
  "0.6.0":
    components:
      "test.7z":
        type: archive
        dest: 'Data'
        hash: false
        optional: true