test.7z:
    files:
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\emblems\allgray.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\app.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\emblems\black.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\emblems\darkblue.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\emblems\darkred.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\dm.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\emblems\gray.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\emblems\green.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\Morrowind.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\old\Morrowind.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\old\Oblivion.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\Oblivion.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\emblems\orange.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\emblems\pink.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\readme.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\emblems\red.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\old\Skyblivion.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\Skyblivion.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\old\Skyrim.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\Skyrim.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\old\Skywind.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\Skywind.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\emblems\violet.png'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\Morrowind.psd'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\Oblivion.psd'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\Skyblivion.psd'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\Skyrim.psd'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\Skywind.psd'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\temp\100.chunk0'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\temp\50.chunk0'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\temp\50.zip.chunk0'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\temp\100.chunk1'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\temp\50.chunk1'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\temp\50.zip.chunk1'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\temp\100.chunk2'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\temp\50.chunk2'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\temp\50.zip.chunk2'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\temp\100.chunks'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\temp\50.chunks'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\temp\50.zip.chunks'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\temp\suspended.list'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\header.tmp'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\temp\header.tmp'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\Skyblivion.yml'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\Skywind.yml'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\uninstall.yml'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\contrib\UnRAR.exe'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\contrib\vcredist_x86_2005.exe'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\contrib\vcredist_x86_2008.exe'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\temp'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\old'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons\emblems'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\icons'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config\contrib'
    - !!python/unicode 'C:\Dropbox\bin\Skywind\Data\config'
    type: archive
